<ul>
  <li>TODO TreeMap of all files, each square size proportional to file changing speed to see what s currently changing</li>
</ul>

<h2>Commit count histogram</h2>
<div id="histogram"></div>

<h2>History</h2>
<h3>Commits count</h3>
<div id="commithist"></div>
<h3>Line changes count</h3>
<div id="linechangedhist"></div>
<h3>Line count</h3>
<div id="linecounthist"></div>

<h2>Day-of-week activity</h2>
<div id="dowcount"></div>


<script src="js/activity.js" type="text/javascript"></script>
