<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Commistory</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="assets/bootstrap-2.0.4/css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="assets/bootstrap-2.0.4/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">

    <script type="text/javascript" src="assets/d3.v2.js"></script>
<!--
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.js?2.3.0"></script>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.csv.js?2.3.0"></script>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.layout.js?2.3.0"></script>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.time.js?2.3.0"></script>
-->
    <style type="text/css">
svg {
  font-family: "Helvetica Neue", Helvetica;
}
    </style>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Commistory</a>
          <div class="nav-collapse">
            <ul class="nav">
              $navitems$
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      $content$
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-transition.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-alert.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-modal.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-dropdown.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-scrollspy.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-tab.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-tooltip.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-popover.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-button.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-collapse.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-carousel.js"></script> -->
    <!-- <script src="assets/bootstrap-2.0.4/js/bootstrap-typeahead.js"></script> -->

  </body>
</html>
