<div class="row">
  <div class="span8">
    <table class="table">
      <thead>
        <tr><th>Repo</th>
            <th>Authors</th>
            <th>Commits</th>
            <th>Active days</th>
            <th>Files</th>
            <th>Size</th>
            <th>++lines</th>
            <th>--lines</th>
        </tr>
      </thead>
      <tbody>
        $tbody$
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="span12">
    <div class="well">
      Generated: $genstamp$
    </div>
  </div>
</div>
